export type CalculatorCategory = 'negocios' | 'laboral' | 'finanzas' | 'tributario';

export interface CalculatorMeta {
  id: string;
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  category: CalculatorCategory;
  tag: string;
  icon: string;
  badge?: string;
  formulaSummary?: string;
  keywords: string[];
}

export interface CategoryInfo {
  id: CalculatorCategory | 'todas';
  label: string;
  icon: string;
  description?: string;
}

export const CATEGORIES: CategoryInfo[] = [
  { id: 'todas', label: 'Todas las calculadoras', icon: 'Calculator' },
  { id: 'negocios', label: 'Negocios & Comercio', icon: 'Store', description: 'Precios, márgenes, recetas y comisiones de cobro' },
  { id: 'laboral', label: 'Laboral & Planilla', icon: 'Briefcase', description: 'Sueldo neto, gratificaciones, CTS, horas extras y vacaciones' },
  { id: 'finanzas', label: 'Finanzas & Metas', icon: 'TrendingUp', description: 'Punto de equilibrio, préstamos, interés compuesto y ROI' },
  { id: 'tributario', label: 'Tributario & Diario', icon: 'Receipt', description: 'IGV 18% SUNAT, 4ta, combustible, dividir cuenta y luz' },
];

export const CALCULATORS_REGISTRY: CalculatorMeta[] = [
  // --- NEGOCIOS & COMERCIO ---
  {
    id: 'precio-de-venta',
    slug: '/precio-de-venta',
    title: 'Calculadora de Precio de Venta Sugerido',
    shortTitle: 'Precio de Venta',
    description: 'Calcula el precio de venta ideal considerando costos, margen real deseado, comisiones de cobro e IGV (18%).',
    category: 'negocios',
    tag: 'COMERCIAL',
    icon: 'ShoppingBag',
    badge: 'Popular',
    formulaSummary: 'Precio Base = Costo Total / (1 - Margen% - Comisión%)',
    keywords: ['precio de venta', 'fijar precios', 'margen comercial', 'mypes peru', 'costo unitario'],
  },
  {
    id: 'margen-de-ganancia',
    slug: '/margen-de-ganancia',
    title: 'Calculadora de Margen de Ganancia y Mark-up',
    shortTitle: 'Margen de Ganancia',
    description: 'Conoce tu margen de utilidad real, utilidad neta por producto y la diferencia exacta frente al mark-up sobre costo.',
    category: 'negocios',
    tag: 'RENTABILIDAD',
    icon: 'TrendingUp',
    badge: 'Esencial',
    formulaSummary: 'Margen (%) = ((Precio Neto - Costo) / Precio Neto) × 100',
    keywords: ['margen de ganancia', 'markup', 'utilidad', 'margen bruto', 'margen neto'],
  },
  {
    id: 'descuentos-y-ofertas',
    slug: '/descuentos-y-ofertas',
    title: 'Calculadora de Descuentos y Rebajas Sucesivas',
    shortTitle: 'Descuentos y Ofertas',
    description: 'Calcula rebajas porcentuales simples y descuentos sucesivos acumulados (ej: 20% + 10% adicional).',
    category: 'negocios',
    tag: 'OFERTAS',
    icon: 'Tag',
    formulaSummary: 'Descuento Único = d1 + d2 - (d1 × d2 / 100)',
    keywords: ['descuentos', 'rebajas', 'ofertas sucesivas', 'cyber wow', 'descuento acumulado'],
  },
  {
    id: 'ganancia-por-producto',
    slug: '/ganancia-por-producto',
    title: 'Calculadora de Ganancia por Producto y Lote',
    shortTitle: 'Ganancia por Producto',
    description: 'Proyecta tu ganancia neta unitaria y total considerando gastos de flete, publicidad o empaque por lote.',
    category: 'negocios',
    tag: 'VENTAS',
    icon: 'PackageCheck',
    formulaSummary: 'Ganancia = (Precio Venta - Costo - Gasto Directo) × Unidades',
    keywords: ['ganancia por lote', 'utilidad unitaria', 'rentabilidad producto', 'comercio'],
  },
  {
    id: 'comisiones-pos-yape',
    slug: '/comisiones-pos-yape',
    title: 'Calculadora de Comisiones POS y Billeteras (Yape, Niubiz, Izipay)',
    shortTitle: 'Comisiones POS y Yape',
    description: 'Calcula cuánto te descuenta Niubiz, Izipay, Culqi, Mercado Pago o Yape Empresa con IGV incluido.',
    category: 'negocios',
    tag: 'PASARELAS',
    icon: 'CreditCard',
    badge: 'Nuevo',
    formulaSummary: 'Comisión Total = Monto × Tasa% × 1.18 (con IGV)',
    keywords: ['comisiones yape empresa', 'comision niubiz pos', 'comision izipay', 'comision culqi', 'mercado pago peru'],
  },
  {
    id: 'costeo-recetas',
    slug: '/costeo-recetas',
    title: 'Calculadora de Costeo de Recetas y Platos (Gastronomía)',
    shortTitle: 'Costeo de Recetas',
    description: 'Calcula el costo por porción, merma de insumos y el precio de carta sugerido para restaurantes, menús y pastelerías.',
    category: 'negocios',
    tag: 'GASTRONOMÍA',
    icon: 'Utensils',
    badge: 'MYPE',
    formulaSummary: 'Costo Porción = (Costo Insumos × (1 + Merma%)) / Porciones',
    keywords: ['costeo gastronomico peru', 'costo por plato restaurante', 'merma de alimentos', 'recetas pasteleria costo'],
  },

  // --- LABORAL & PLANILLA ---
  {
    id: 'sueldo-neto',
    slug: '/sueldo-neto',
    title: 'Calculadora de Sueldo Neto Perú (AFP vs ONP + 5ta Categoría)',
    shortTitle: 'Sueldo Neto',
    description: 'Calcula cuánto recibirás en mano en tu cuenta bancaria descontando tu AFP (Integra, Prima, Profuturo, Habitat) o el 13% de ONP y el impuesto de 5ta.',
    category: 'laboral',
    tag: 'PLANILLA',
    icon: 'Briefcase',
    badge: 'Más buscado',
    formulaSummary: 'Neto = Sueldo Bruto + Asig. Fam - Descuento Pensión - 5ta Categoría',
    keywords: ['sueldo neto peru', 'calcular sueldo en mano', 'afp integra descuento', 'onp 13 por ciento', 'retencion quinta categoria'],
  },
  {
    id: 'gratificacion',
    slug: '/gratificacion',
    title: 'Calculadora de Gratificación (Julio y Diciembre + 9% EsSalud)',
    shortTitle: 'Gratificaciones',
    description: 'Calcula el pago de gratificaciones legales de Fiestas Patrias y Navidad con la bonificación extraordinaria de EsSalud (9%) o EPS (6.75%).',
    category: 'laboral',
    tag: 'BENEFICIOS',
    icon: 'Gift',
    badge: 'Legal',
    formulaSummary: 'Total Grati = (Sueldo Computable × Meses / 6) + Bonificación 9%',
    keywords: ['calcular gratificacion julio', 'gratificacion navidad', 'bono essalud 9 por ciento', 'gratificacion regimen general mype'],
  },
  {
    id: 'calculadora-cts',
    slug: '/calculadora-cts',
    title: 'Calculadora de CTS (Depósitos de Mayo y Noviembre)',
    shortTitle: 'Depósito de CTS',
    description: 'Calcula cuánto debe depositarte tu empleador por Compensación por Tiempo de Servicios según los meses laborados y el sexto de gratificación.',
    category: 'laboral',
    tag: 'BENEFICIOS',
    icon: 'PiggyBank',
    badge: 'Legal',
    formulaSummary: 'CTS = (Sueldo + 1/6 Gratificación) / 12 × Meses laborados',
    keywords: ['calcular cts mayo', 'cts noviembre peru', 'deposito cts banco', 'compensacion tiempo servicios'],
  },
  {
    id: 'horas-extras',
    slug: '/horas-extras',
    title: 'Calculadora de Horas Extras Perú (25%, 35% y Feriados 100%)',
    shortTitle: 'Horas Extras',
    description: 'Calcula el pago exacto de tus horas extras: 25% para las dos primeras horas, 35% para las restantes y 100% en feriados.',
    category: 'laboral',
    tag: 'SOBRETASA',
    icon: 'Clock',
    badge: 'Planilla',
    formulaSummary: 'Hora Extra = Valor Hora × (1 + Sobretasa%)',
    keywords: ['horas extras peru', 'calcular hora extra 25 35', 'pago feriado trabajado', 'sobretasa horas extras ley'],
  },
  {
    id: 'calculadora-vacaciones',
    slug: '/calculadora-vacaciones',
    title: 'Calculadora de Vacaciones Truncas y Venta de Vacaciones',
    shortTitle: 'Vacaciones Truncas',
    description: 'Calcula el pago de vacaciones no gozadas, truncas por cese laboral o la venta legal de hasta 15 días según el D.L. 713.',
    category: 'laboral',
    tag: 'DESCANSO',
    icon: 'Palmtree',
    badge: 'Legal',
    formulaSummary: 'Vacaciones = (Sueldo Computable / 12) × Meses Laborados',
    keywords: ['vacaciones truncas peru', 'venta de vacaciones dl 713', 'pago vacaciones no gozadas', 'liquidacion vacaciones'],
  },

  // --- FINANZAS & METAS ---
  {
    id: 'punto-de-equilibrio',
    slug: '/punto-de-equilibrio',
    title: 'Calculadora de Punto de Equilibrio (Break-Even)',
    shortTitle: 'Punto de Equilibrio',
    description: 'Descubre cuántas unidades y cuántos Soles debes vender cada mes para cubrir costos fijos y variables sin entrar en pérdidas.',
    category: 'finanzas',
    tag: 'NEGOCIOS',
    icon: 'Scale',
    badge: 'MYPE',
    formulaSummary: 'Unidades = Costos Fijos / (Precio - Costo Variable)',
    keywords: ['punto de equilibrio', 'breakeven', 'costos fijos', 'margen de contribucion'],
  },
  {
    id: 'ventas-necesarias',
    slug: '/ventas-necesarias',
    title: 'Calculadora de Ventas Necesarias para una Ganancia Deseada',
    shortTitle: 'Ventas Necesarias',
    description: 'Calcula cuántas unidades y facturación necesitas alcanzar para obtener una ganancia neta específica por encima de tus costos.',
    category: 'finanzas',
    tag: 'METAS',
    icon: 'Target',
    formulaSummary: 'Unidades = (Costos Fijos + Meta Ganancia) / Margen Contribución',
    keywords: ['ventas necesarias', 'meta de ventas', 'plan comercial', 'utilidad deseada'],
  },
  {
    id: 'recuperacion-de-inversion',
    slug: '/recuperacion-de-inversion',
    title: 'Calculadora de Recuperación de Inversión (ROI y Payback)',
    shortTitle: 'Retorno de Inversión (ROI)',
    description: 'Estima en cuántos meses recuperarás tu capital invertido y cuál es el porcentaje de retorno anualizado de tu proyecto.',
    category: 'finanzas',
    tag: 'INVERSIÓN',
    icon: 'PiggyBank',
    formulaSummary: 'Payback (Meses) = Inversión Inicial / Ganancia Neta Mensual',
    keywords: ['roi peru', 'payback', 'retorno de inversion', 'recuperar capital', 'inversion negocio'],
  },
  {
    id: 'prestamo-bancario',
    slug: '/prestamo-bancario',
    title: 'Simulador de Préstamos y Cuotas Bancarias (Sistema Francés)',
    shortTitle: 'Cuotas de Préstamo',
    description: 'Calcula tu cuota mensual fija en Soles, intereses totales y seguro de desgravamen según la TEA de bancos o cajas del Perú.',
    category: 'finanzas',
    tag: 'CRÉDITOS',
    icon: 'Landmark',
    badge: 'Financiero',
    formulaSummary: 'Cuota Francesa = Monto × [TEM(1+TEM)^n] / [(1+TEM)^n - 1]',
    keywords: ['simulador de prestamo bcp bbva interbank', 'cuota mensual prestamo', 'tea interes prestamo', 'sistema frances cuotas'],
  },
  {
    id: 'interes-compuesto',
    slug: '/interes-compuesto',
    title: 'Simulador de Interés Compuesto y Ahorro en Cajas / Bancos',
    shortTitle: 'Interés Compuesto',
    description: 'Calcula cuánto crecerán tus ahorros o depósitos a plazo fijo con aportes mensuales y tasas TREA de entidades financieras.',
    category: 'finanzas',
    tag: 'AHORRO',
    icon: 'LineChart',
    badge: 'Crecimiento',
    formulaSummary: 'VF = VP × (1 + i)^n + PMT × [((1 + i)^n - 1) / i]',
    keywords: ['interes compuesto peru', 'deposito a plazo fijo trea', 'caja huancayo ahorro', 'inversion interes compuesto'],
  },
  {
    id: 'porcentajes',
    slug: '/porcentajes',
    title: 'Calculadora de Porcentajes Rápidos',
    shortTitle: 'Porcentajes',
    description: 'Calcula el X% de una cantidad, qué porcentaje representa A de B y aumentos o disminuciones porcentuales.',
    category: 'finanzas',
    tag: 'BÁSICOS',
    icon: 'Percent',
    formulaSummary: 'X% de Y = (X / 100) × Y',
    keywords: ['calculadora de porcentaje', 'sacar porcentaje', 'variacion porcentual', 'regla de tres'],
  },

  // --- TRIBUTARIO & SERVICIOS ---
  {
    id: 'calculadora-igv',
    slug: '/calculadora-igv',
    title: 'Calculadora de IGV (18% SUNAT - Agregar o Extraer)',
    shortTitle: 'Calculadora IGV (18%)',
    description: 'Calcula el 18% de IGV (16% IGV + 2% IPM) o extrae la base imponible y el impuesto de cualquier monto facturado en el Perú.',
    category: 'tributario',
    tag: 'TRIBUTARIA',
    icon: 'Receipt',
    badge: 'Oficial',
    formulaSummary: 'Extraer IGV: Base = Total / 1.18 | Agregar IGV: Total = Base × 1.18',
    keywords: ['calculadora igv peru', 'extraer igv 18', 'sunat igv', 'factura con igv', 'base imponible'],
  },
  {
    id: 'recibo-por-honorarios',
    slug: '/recibo-por-honorarios',
    title: 'Calculadora de Recibos por Honorarios (4ta Categoría - Retención 8%)',
    shortTitle: 'Recibo por Honorarios',
    description: 'Calcula la retención del 8% de Impuesto a la Renta de 4ta Categoría de SUNAT para trabajadores independientes y el monto neto a cobrar.',
    category: 'tributario',
    tag: 'HONORARIOS',
    icon: 'FileText',
    badge: 'Independientes',
    formulaSummary: 'Retención (8%) = Monto Bruto × 0.08 (si supera S/ 1,500)',
    keywords: ['recibo por honorarios sunat', 'retencion 8 por ciento', 'cuarta categoria', 'suspension retenciones 4ta'],
  },
  {
    id: 'dividir-cuenta',
    slug: '/dividir-cuenta',
    title: 'Calculadora de Dividir Cuenta y Propina (¿Cuánto me yapeas?)',
    shortTitle: 'Dividir la Cuenta',
    description: 'Divide la cuenta de un restaurante, pollería o bar entre amigos con propina opcional y calcula cuánto le toca transferir a cada uno.',
    category: 'tributario',
    tag: 'DIARIO',
    icon: 'Utensils',
    badge: 'Amigos',
    formulaSummary: 'Por Persona = (Total Cuenta + Propina) / N° Personas',
    keywords: ['dividir cuenta restaurante', 'cuanto me yapeas', 'calcular propina peru', 'separar cuenta amigos'],
  },
  {
    id: 'gasto-combustible',
    slug: '/gasto-combustible',
    title: 'Calculadora de Combustible y Gasto de Viaje en Soles',
    shortTitle: 'Gasto de Combustible',
    description: 'Calcula los galones necesarios, el gasto total en Soles y el costo por persona para viajes en carretera o traslados diarios.',
    category: 'tributario',
    tag: 'TRANSPORTE',
    icon: 'Fuel',
    badge: 'Viajes',
    formulaSummary: 'Costo = (Distancia / Rendimiento) × Precio Combustible',
    keywords: ['consumo de gasolina viaje', 'calcular gasto gasolina carretera', 'precio galon 90 95 soles', 'costo por km peru'],
  },
  {
    id: 'consumo-electrico',
    slug: '/consumo-electrico',
    title: 'Calculadora de Consumo Eléctrico y Recibo de Luz',
    shortTitle: 'Consumo Eléctrico',
    description: 'Calcula el gasto mensual en Soles de tus electrodomésticos según las tarifas en kWh de Luz del Sur, Enel o empresas regionales.',
    category: 'tributario',
    tag: 'SERVICIOS',
    icon: 'Zap',
    badge: 'Tarifario',
    formulaSummary: 'Gasto Mensual = (Watts × Horas/día × Días/mes / 1000) × Tarifa kWh',
    keywords: ['consumo electrico luz del sur', 'recibo de luz enel', 'gasto kwh soles', 'electrodomesticos consumo'],
  },
];
