export type CalculatorCategory = 'negocios' | 'laboral' | 'finanzas' | 'tributario';

export interface CalculatorMeta {
  id: string;
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  cardSummary: string; // 1-line concise summary for home cards
  category: CalculatorCategory;
  tag: string;
  icon: string;
  badge?: string;
  formulaSummary?: string;
  keywords: string[];
}

export interface CategoryInfo {
  id: CalculatorCategory | 'todas';
  label: string;
  icon: string;
  description?: string;
}

export const CATEGORIES: CategoryInfo[] = [
  { id: 'todas', label: 'Todas las calculadoras', icon: 'Calculator' },
  { id: 'negocios', label: 'Negocios & Comercio', icon: 'Store', description: 'Precios, márgenes, recetas y comisiones de cobro' },
  { id: 'laboral', label: 'Laboral & Planilla', icon: 'Briefcase', description: 'Sueldo neto, gratificaciones, CTS, horas extras y vacaciones' },
  { id: 'finanzas', label: 'Finanzas & Metas', icon: 'TrendingUp', description: 'Punto de equilibrio, préstamos, interés compuesto y ROI' },
  { id: 'tributario', label: 'Tributario & Diario', icon: 'Receipt', description: 'IGV 18% SUNAT, 4ta, combustible, dividir cuenta y luz' },
];

export function getCalculatorCode(calc: CalculatorMeta): string {
  const categoryCodeMap: Record<CalculatorCategory, string> = {
    negocios: 'COM',
    laboral: 'LAB',
    finanzas: 'FIN',
    tributario: 'TRI',
  };
  const sameCategory = CALCULATORS_REGISTRY.filter(c => c.category === calc.category);
  const index = sameCategory.findIndex(c => c.id === calc.id) + 1;
  const prefix = categoryCodeMap[calc.category] || 'GEN';
  return `${String(index).padStart(3, '0')}-${prefix}`;
}

export const CALCULATORS_REGISTRY: CalculatorMeta[] = [
  // --- NEGOCIOS & COMERCIO ---
  {
    id: 'precio-de-venta',
    slug: '/precio-de-venta',
    title: 'Calculadora de Precio de Venta Sugerido',
    shortTitle: 'Precio de Venta Sugerido',
    description: 'Calcula el precio de venta ideal considerando costos, margen real deseado, comisiones de cobro e IGV (18%).',
    cardSummary: 'Calcula tu precio de venta ideal',
    category: 'negocios',
    tag: 'COMERCIAL',
    icon: 'ShoppingBag',
    badge: 'Popular',
    formulaSummary: 'Precio Base = Costo Total / (1 - Margen% - Comisión%)',
    keywords: ['precio de venta', 'fijar precios', 'margen comercial', 'mypes peru', 'costo unitario'],
  },
  {
    id: 'margen-de-ganancia',
    slug: '/margen-de-ganancia',
    title: 'Calculadora de Margen de Ganancia y Mark-up',
    shortTitle: 'Margen de Ganancia y Mark-up',
    description: 'Conoce tu margen de utilidad real, utilidad neta por producto y la diferencia exacta frente al mark-up sobre costo.',
    cardSummary: 'Conoce tu margen de utilidad real y utilidad neta',
    category: 'negocios',
    tag: 'RENTABILIDAD',
    icon: 'TrendingUp',
    badge: 'Esencial',
    formulaSummary: 'Margen (%) = ((Precio Neto - Costo) / Precio Neto) × 100',
    keywords: ['margen de ganancia', 'markup', 'utilidad', 'margen bruto', 'margen neto'],
  },
  {
    id: 'descuentos-y-ofertas',
    slug: '/descuentos-y-ofertas',
    title: 'Calculadora de Descuentos y Rebajas Sucesivas',
    shortTitle: 'Descuentos y Rebajas Sucesivas',
    description: 'Calcula rebajas porcentuales simples y descuentos sucesivos acumulados (ej: 20% + 10% adicional).',
    cardSummary: 'Calcula rebajas simples o acumuladas',
    category: 'negocios',
    tag: 'OFERTAS',
    icon: 'Tag',
    formulaSummary: 'Descuento Único = d1 + d2 - (d1 × d2 / 100)',
    keywords: ['descuentos', 'rebajas', 'ofertas sucesivas', 'cyber wow', 'descuento acumulado'],
  },
  {
    id: 'ganancia-por-producto',
    slug: '/ganancia-por-producto',
    title: 'Calculadora de Ganancia por Producto y Lote',
    shortTitle: 'Ganancia por Producto y Lote',
    description: 'Proyecta tu ganancia neta unitaria y total considerando gastos de flete, publicidad o empaque por lote.',
    cardSummary: 'Proyecta tu ganancia por unidad o por lote',
    category: 'negocios',
    tag: 'VENTAS',
    icon: 'PackageCheck',
    formulaSummary: 'Ganancia = (Precio Venta - Costo - Gasto Directo) × Unidades',
    keywords: ['ganancia por lote', 'utilidad unitaria', 'rentabilidad producto', 'comercio'],
  },
  {
    id: 'comisiones-pos-yape',
    slug: '/comisiones-pos-yape',
    title: 'Calculadora de Comisiones POS y Billeteras (Yape, Niubiz, Izipay)',
    shortTitle: 'Comisiones POS y Billeteras',
    description: 'Calcula cuánto te descuenta Niubiz, Izipay, Culqi, Mercado Pago o Yape Empresa con IGV incluido.',
    cardSummary: 'Calcula comisiones de Yape, Niubiz, Izipay y más',
    category: 'negocios',
    tag: 'PASARELAS',
    icon: 'CreditCard',
    badge: 'Nuevo',
    formulaSummary: 'Comisión Total = Monto × Tasa% × 1.18 (con IGV)',
    keywords: ['comisiones yape empresa', 'comision niubiz pos', 'comision izipay', 'comision culqi', 'mercado pago peru'],
  },
  {
    id: 'costeo-recetas',
    slug: '/costeo-recetas',
    title: 'Calculadora de Costeo de Recetas y Platos (Gastronomía)',
    shortTitle: 'Costeo de Recetas y Platos',
    description: 'Calcula el costo por porción, merma de insumos y el precio de carta sugerido para restaurantes, menús y pastelerías.',
    cardSummary: 'Calcula el costo por porción y el precio sugerido',
    category: 'negocios',
    tag: 'GASTRONOMÍA',
    icon: 'Utensils',
    badge: 'MYPE',
    formulaSummary: 'Costo Porción = (Costo Insumos × (1 + Merma%)) / Porciones',
    keywords: ['costeo gastronomico peru', 'costo por plato restaurante', 'merma de alimentos', 'recetas pasteleria costo'],
  },

  // --- LABORAL & PLANILLA ---
  {
    id: 'sueldo-neto',
    slug: '/sueldo-neto',
    title: 'Calculadora de Sueldo Neto Perú (AFP vs ONP + 5ta Categoría)',
    shortTitle: 'Sueldo Neto Perú (AFP vs ONP + 5ta)',
    description: 'Calcula cuánto recibirás en mano en tu cuenta bancaria descontando tu AFP (Integra, Prima, Profuturo, Habitat) o el 13% de ONP y el impuesto de 5ta.',
    cardSummary: 'Calcula tu sueldo neto fácil y rápido',
    category: 'laboral',
    tag: 'PLANILLA',
    icon: 'Briefcase',
    badge: 'Más buscado',
    formulaSummary: 'Neto = Sueldo Bruto + Asig. Fam - Descuento Pensión - 5ta Categoría',
    keywords: ['sueldo neto peru', 'calcular sueldo en mano', 'afp integra descuento', 'onp 13 por ciento', 'retencion quinta categoria'],
  },
  {
    id: 'gratificacion',
    slug: '/gratificacion',
    title: 'Calculadora de Gratificación (Julio y Diciembre + 9% EsSalud)',
    shortTitle: 'Gratificación (Julio y Diciembre)',
    description: 'Calcula el pago de gratificaciones legales de Fiestas Patrias y Navidad con la bonificación extraordinaria de EsSalud (9%) o EPS (6.75%).',
    cardSummary: 'Calcula tu gratificación de forma rápida y precisa',
    category: 'laboral',
    tag: 'BENEFICIOS',
    icon: 'Gift',
    badge: 'Legal',
    formulaSummary: 'Total Grati = (Sueldo Computable × Meses / 6) + Bonificación 9%',
    keywords: ['calcular gratificacion julio', 'gratificacion navidad', 'bono essalud 9 por ciento', 'gratificacion regimen general mype'],
  },
  {
    id: 'calculadora-cts',
    slug: '/calculadora-cts',
    title: 'Calculadora de CTS (Depósitos de Mayo y Noviembre)',
    shortTitle: 'CTS (Depósitos de Mayo y Noviembre)',
    description: 'Calcula cuánto debe depositarte tu empleador por Compensación por Tiempo de Servicios según los meses laborados y el sexto de gratificación.',
    cardSummary: 'Calcula cuánto debe depositarte tu empleador',
    category: 'laboral',
    tag: 'BENEFICIOS',
    icon: 'PiggyBank',
    badge: 'Legal',
    formulaSummary: 'CTS = (Sueldo + 1/6 Gratificación) / 12 × Meses laborados',
    keywords: ['calcular cts mayo', 'cts noviembre peru', 'deposito cts banco', 'compensacion tiempo servicios'],
  },
  {
    id: 'horas-extras',
    slug: '/horas-extras',
    title: 'Calculadora de Horas Extras Perú (25%, 35% y Feriados 100%)',
    shortTitle: 'Horas Extras (25%, 35% y Feriados)',
    description: 'Calcula el pago exacto de tus horas extras: 25% para las dos primeras horas, 35% para las restantes y 100% en feriados.',
    cardSummary: 'Calcula horas al 25%, 35% y feriados al 100%',
    category: 'laboral',
    tag: 'SOBRETASA',
    icon: 'Clock',
    badge: 'Planilla',
    formulaSummary: 'Hora Extra = Valor Hora × (1 + Sobretasa%)',
    keywords: ['horas extras peru', 'calcular hora extra 25 35', 'pago feriado trabajado', 'sobretasa horas extras ley'],
  },
  {
    id: 'calculadora-vacaciones',
    slug: '/calculadora-vacaciones',
    title: 'Calculadora de Vacaciones Truncas y Venta de Vacaciones',
    shortTitle: 'Vacaciones Truncas y Venta D.L. 713',
    description: 'Calcula el pago de vacaciones no gozadas, truncas por cese laboral o la venta legal de hasta 15 días según el D.L. 713.',
    cardSummary: 'Calcula liquidación de vacaciones y venta de días',
    category: 'laboral',
    tag: 'DESCANSO',
    icon: 'Palmtree',
    badge: 'Legal',
    formulaSummary: 'Vacaciones = (Sueldo Computable / 12) × Meses Laborados',
    keywords: ['vacaciones truncas peru', 'venta de vacaciones dl 713', 'pago vacaciones no gozadas', 'liquidacion vacaciones'],
  },

  // --- FINANZAS & METAS ---
  {
    id: 'punto-de-equilibrio',
    slug: '/punto-de-equilibrio',
    title: 'Calculadora de Punto de Equilibrio (Break-Even)',
    shortTitle: 'Punto de Equilibrio MYPE',
    description: 'Descubre cuántas unidades o cuánto dinero en soles necesitas vender al mes para cubrir todos tus costos fijos y variables sin perder.',
    cardSummary: 'Calcula cuántas unidades debes vender para no perder',
    category: 'finanzas',
    tag: 'FINANZAS',
    icon: 'Scale',
    formulaSummary: 'Punto Equilibrio = Costos Fijos / (Precio - Costo Variable)',
    keywords: ['punto de equilibrio', 'umbral de rentabilidad', 'costos fijos', 'mype finanzas'],
  },
  {
    id: 'ventas-necesarias',
    slug: '/ventas-necesarias',
    title: 'Calculadora de Ventas Necesarias para Ganancia Deseada',
    shortTitle: 'Ventas Necesarias para Utilidad',
    description: 'Calcula exactamente cuántas ventas o ingresos requieres para alcanzar tu meta de ganancia líquida mensual en soles.',
    cardSummary: 'Calcula las ventas requeridas para tu meta de utilidad',
    category: 'finanzas',
    tag: 'METAS',
    icon: 'Target',
    formulaSummary: 'Ventas = (Costos Fijos + Meta Ganancia) / Margen Contribución',
    keywords: ['meta de ventas', 'proyeccion ingresos', 'cuanto vender', 'plan comercial'],
  },
  {
    id: 'recuperacion-de-inversion',
    slug: '/recuperacion-de-inversion',
    title: 'Calculadora de Recuperación de Inversión (ROI y Payback)',
    shortTitle: 'Recuperación de Inversión (ROI)',
    description: 'Evalúa la rentabilidad porcentual de un proyecto o negocio y en cuántos meses exactos recuperarás el capital invertido.',
    cardSummary: 'Calcula el retorno de inversión y meses de recuperación',
    category: 'finanzas',
    tag: 'INVERSIÓN',
    icon: 'LineChart',
    formulaSummary: 'ROI (%) = ((Ganancia - Inversión) / Inversión) × 100',
    keywords: ['roi peru', 'payback', 'retorno inversion', 'evaluar negocio'],
  },
  {
    id: 'prestamo-bancario',
    slug: '/prestamo-bancario',
    title: 'Simulador de Préstamos Bancarios y Cuotas (Sistema Francés)',
    shortTitle: 'Préstamo Bancario (Cuotas)',
    description: 'Simula las cuotas mensuales de préstamos personales, vehiculares o capital de trabajo para MYPES en entidades financieras del Perú.',
    cardSummary: 'Simula cuotas mensuales y cronograma francés',
    category: 'finanzas',
    tag: 'CRÉDITO',
    icon: 'Landmark',
    badge: 'Bancos',
    formulaSummary: 'Cuota = [P × i × (1 + i)^n] / [(1 + i)^n - 1]',
    keywords: ['simulador prestamo bcp bbva', 'prestamo caja municipal', 'cuota credito personal', 'sistema frances peru'],
  },
  {
    id: 'interes-compuesto',
    slug: '/interes-compuesto',
    title: 'Calculadora de Interés Compuesto y Ahorro en Cajas/Bancos',
    shortTitle: 'Interés Compuesto y Ahorro',
    description: 'Simula el crecimiento de tus ahorros e inversiones a plazo fijo en bancos y cajas municipales peruanas con aportes mensuales y TREA.',
    cardSummary: 'Simula el crecimiento de tus ahorros en bancos y cajas',
    category: 'finanzas',
    tag: 'AHORRO',
    icon: 'TrendingUp',
    badge: 'Cajas',
    formulaSummary: 'Monto Final = Capital × (1 + r/n)^(n×t)',
    keywords: ['interes compuesto peru', 'deposito a plazo fijo cajas', 'trea bancos peru', 'crecimiento ahorros'],
  },
  {
    id: 'porcentajes',
    slug: '/porcentajes',
    title: 'Calculadora de Porcentajes Rápidos',
    shortTitle: 'Calculadora de Porcentajes',
    description: 'Calcula rápidamente qué porcentaje representa un número de otro, aumentos, disminuciones y variaciones porcentuales.',
    cardSummary: 'Calcula porcentajes rápidos de aumento o rebaja',
    category: 'finanzas',
    tag: 'UTILIDAD',
    icon: 'Percent',
    formulaSummary: 'Porcentaje = (Parte / Total) × 100',
    keywords: ['porcentajes', 'sacar porcentaje', 'variacion porcentual', 'regla de tres'],
  },

  // --- TRIBUTARIO & DIARIO ---
  {
    id: 'calculadora-igv',
    slug: '/calculadora-igv',
    title: 'Calculadora de IGV (18% SUNAT)',
    shortTitle: 'Calculadora de IGV (18%)',
    description: 'Calcula o desglosa el 18% de IGV oficial en compras y ventas de Perú (base imponible, impuesto y total facturado).',
    cardSummary: 'Calcula o desglosa el 18% de IGV SUNAT',
    category: 'tributario',
    tag: 'SUNAT',
    icon: 'Receipt',
    badge: 'Oficial',
    formulaSummary: 'Total = Base × 1.18 | IGV = Total - (Total / 1.18)',
    keywords: ['igv peru', 'calcular igv 18', 'sacar igv factura', 'base imponible sunat', 'desglosar igv'],
  },
  {
    id: 'recibo-por-honorarios',
    slug: '/recibo-por-honorarios',
    title: 'Calculadora de Recibo por Honorarios (4ta Categoría - Retención 8%)',
    shortTitle: 'Recibo por Honorarios (4ta Cat)',
    description: 'Calcula el monto neto a cobrar o el monto bruto a emitir en tu recibo por honorarios electrónico descontando la retención del 8% de SUNAT.',
    cardSummary: 'Calcula la retención del 8% de 4ta categoría',
    category: 'tributario',
    tag: 'SUNAT',
    icon: 'FileText',
    badge: 'Legal',
    formulaSummary: 'Retención = Monto Bruto × 8% (para montos > S/ 1,500)',
    keywords: ['recibo por honorarios sunat', 'retencion 8 por ciento', 'cuarta categoria peru', 'suspension retenciones'],
  },
  {
    id: 'dividir-cuenta',
    slug: '/dividir-cuenta',
    title: 'Calculadora para Dividir la Cuenta y Propina (Yape / Plin)',
    shortTitle: 'Dividir Cuenta y Propina',
    description: 'Divide la cuenta de un restaurante, almuerzo o reunión entre amigos de forma justa en soles y calcula la propina voluntaria para Yapear.',
    cardSummary: 'Divide la cuenta y propinas entre amigos para Yapear',
    category: 'tributario',
    tag: 'DIARIO',
    icon: 'Utensils',
    badge: 'Amigos',
    formulaSummary: 'Total por Persona = (Cuenta Total + Propina) / Personas',
    keywords: ['dividir cuenta restaurante', 'cuanto yapear cuenta', 'calcular propina peru', 'pagar entre amigos'],
  },
  {
    id: 'gasto-combustible',
    slug: '/gasto-combustible',
    title: 'Calculadora de Gasto de Combustible y Viaje en Soles',
    shortTitle: 'Gasto de Combustible y Viaje',
    description: 'Calcula cuántos galones de gasolina, GLP, GNV o diésel necesitas para tu viaje en carretera o delivery y cuánto cuesta por pasajero.',
    cardSummary: 'Calcula galones necesarios y costo de viaje en soles',
    category: 'tributario',
    tag: 'VIAJES',
    icon: 'Fuel',
    badge: 'Ruta',
    formulaSummary: 'Costo Total = (Distancia / Rendimiento) × Precio Combustible',
    keywords: ['gasto gasolina viaje peru', 'calculadora combustible soles', 'costo por km viaje', 'viaje lima provincias gasolina'],
  },
  {
    id: 'liquidacion-laboral',
    slug: '/liquidacion-laboral',
    title: 'Calculadora de Liquidación Laboral Todo en 1 (Beneficios y Despido)',
    shortTitle: 'Liquidación Laboral Todo en 1',
    description: 'Calcula tu liquidación completa ante cese o despido: CTS trunca, gratificación, bono EsSalud, vacaciones truncas e indemnización legal.',
    cardSummary: 'Calcula tu liquidación total: CTS, Grati, Vacaciones y Despido',
    category: 'laboral',
    tag: 'PLANILLA',
    icon: 'Briefcase',
    badge: 'Completo',
    formulaSummary: 'Total = CTS Trunca + Grati Trunca + Bono 9% + Vacaciones + Indemnización',
    keywords: ['liquidacion laboral peru', 'calcular liquidacion', 'cuanto me pagan por renuncia', 'indemnizacion despido arbitrario', 'cts grati vacaciones truncas'],
  },
  {
    id: 'tipo-de-cambio-dolar-sunat',
    slug: '/tipo-de-cambio-dolar-sunat',
    title: 'Calculadora de Tipo de Cambio Dólar / Soles Hoy',
    shortTitle: 'Tipo de Cambio Dólar / Soles',
    description: 'Convierte dólares a soles automáticamente con la tasa USD/PEN actualizada y consulta también la última compra y venta SBS publicada mediante BCRPData.',
    cardSummary: 'Convierte dólares y soles con una tasa actualizada automáticamente',
    category: 'tributario',
    tag: 'DÓLAR',
    icon: 'DollarSign',
    badge: 'Actualizado',
    formulaSummary: 'Total PEN = Monto USD × Tipo Cambio Compra | Total USD = Monto PEN / Venta',
    keywords: ['tipo de cambio sunat', 'dolar a soles', 'precio del dolar hoy', 'tipo de cambio sbs', 'cambiar dolares peru'],
  },
  {
    id: 'consumo-electrico',
    slug: '/consumo-electrico',
    title: 'Calculadora de Consumo Eléctrico y Recibo de Luz',
    shortTitle: 'Consumo de Luz y Recibo',
    description: 'Estima el gasto mensual en Soles de tus artefactos eléctricos y electrodomésticos según las tarifas de Osinergmin.',
    cardSummary: 'Calcula tu consumo de kWh y monto de luz',
    category: 'tributario',
    tag: 'SERVICIOS',
    icon: 'Zap',
    formulaSummary: 'Costo = (Watts × Horas/día × 30 / 1000) × Tarifa S/ kWh',
    keywords: ['consumo electrico peru', 'recibo de luz', 'luz del sur enel', 'cuanto gasta refrigeradora'],
  },
  {
    id: 'regimenes-tributarios-sunat',
    slug: '/regimenes-tributarios-sunat',
    title: 'Simulador de Regímenes Tributarios SUNAT (RUS, RER, MYPE y General)',
    shortTitle: 'Regímenes Tributarios SUNAT',
    description: 'Descubre en qué régimen tributario de la SUNAT te conviene inscribir tu negocio (RUS, RER, RMT o General) y cuánto pagarás de impuestos.',
    cardSummary: 'Simula qué régimen SUNAT te conviene (RUS, RER, MYPE)',
    category: 'tributario',
    tag: 'SUNAT',
    icon: 'Building',
    badge: 'MYPE',
    formulaSummary: 'Diagnóstico por Topes Anuales: RUS (S/ 96k), RER (S/ 525k), RMT (1,700 UIT)',
    keywords: ['regimenes tributarios sunat', 'nuevo rus rer rmt general', 'que regimen me conviene', 'impuestos sunat mype', 'cuanto pago en el rus'],
  },
];
